version: '3.8'

services:
  # Auth Service Database
  auth-db:
    image: postgres:17-alpine
    container_name: onestopshop-auth-db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_dev_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./init-scripts/auth:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - onestopshop-network


volumes:
  auth_db_data:

networks:
  onestopshop-network:
    driver: bridge
